@echo off
rem copy .\*.qvs .\QLib.lib /Y

echo // Autogenerated QLib Full Library > QLibFull.qvs

for %%a in (*.qvs) do (
	echo %%a
	if NOT [%%a] == [QLib.qvs] (
		if NOT [%%a] == [QLibFull.qvs] (
			type "%%a" >> QLibFull.qvs
		)
	)
)